### ISSUE TITLE
st2mistral doesn't have versioning

### ISSUE THREAD

**Issue by dennybaa** [StackStorm/st2mistral#12]
Versioning is required to build packages, we can build with version 0.1 always or whatever.
But it would be nice to see it, better in the same way as for st2 components, i.e. 
`__init__.py` contains:

```
__version__ = '0.1.0' # or anything what you like ...
```

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1453484954030365

**Comment by m4dcoder** [comment]
Can it be made the same version as the mistral package that it is included in?
