### ISSUE TITLE
ERROR (app) 'NoneType' object has no attribute 'get_trace_id_headers'

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2mistral#21]
Hello,

Getting that message on almost every command I give to mistral from the CLI. Mistral workflows work fine in Stackstorm, though.

```
$ mistral workflow-list
ERROR (app) 'NoneType' object has no attribute 'get_trace_id_headers'
```

If I recall correctly, it started to fail after 2.0.0->2.0.1 upgrade. Is it just me or everyone else?

**Comment by lightsey** [comment]
I'm seeing the same problem with mistral version 2.1.1.

httpclient.py has an optional import of 'osprofiler.web', then it uses osprofiler.web without verifying it actually loaded.

The simple workaround is to install osprofiler using pip.
